server:
    contextPath: ${hubadmin.contextpath:/hub-admin}

endpoints:
    enabled: false
    health:
        enabled: ${hubadmin.endpoints.health.enabled:true}
    metrics:
        enabled: ${hubadmin.endpoints.metrics.enabled:true}

spring:
  http:
    multipart:
      max-file-size: 5MB
