server:
    contextPath: ${hubadmin.contextpath:/hub-admin}
    port: 8090

endpoints:
    enabled: false
    health:
        enabled: ${hubadmin.endpoints.health.enabled:true}
    metrics:
        enabled: ${hubadmin.endpoints.metrics.enabled:true}

spring:
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

security:
  user:
    name: ${basic.auth.username:user}
    password: ${basic.auth.password:password}